use_frameworks!

source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'

target 'LZNetworkingHelper_Example' do
  pod 'LZNetworkingHelper', :path => '../'

  target 'LZNetworkingHelper_Tests' do
    inherit! :search_paths

  end
end
