use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'LZNetworkingHelper_Example' do
  pod 'LZNetworkingHelper', :path => '../'

  target 'LZNetworkingHelper_Tests' do
    inherit! :search_paths

  end
end
